export { default as Dashboard } from '@/dashboard'
export { default as ErrorPage } from '@/error-page'
export { default as Login } from '@/pages/Auth/Login'
export { default as Home } from '@/pages/Home'
export { default as Categories } from '@/pages/Menu/Categories/Categories'
export { default as CategoryId } from '@/pages/Menu/Categories/categoryId'
export { default as CreateCategory } from '@/pages/Menu/Categories/createCategory'
export { default as MenuMakerLayout } from '@/pages/Menu/MenuMakerLayout'
export { default as CreateMenu } from '@/pages/Menu/Menus/createMenu'
export { default as Menus } from '@/pages/Menu/Menus/Menus'
export { default as ModifierGroups } from '@/pages/Menu/Modifiers/ModifierGroups'
export { default as MenuOverview } from '@/pages/Menu/MenuOverview'
export { default as CreateProduct } from '@/pages/Menu/Products/createProduct'
export { default as ProductId } from '@/pages/Menu/Products/productId'
export { default as Products } from '@/pages/Menu/Products/Products'
export { default as CreateTpv } from '@/pages/Tpv/createTpv'
export { default as Tpv } from '@/pages/Tpv/Tpvs'
export { default as TpvId } from '@/pages/Tpv/TpvId'
export { default as Account } from '@/pages/Account/Account'
export { default as Payments } from '@/pages/Payment/Payments'
export { default as PaymentId } from '@/pages/Payment/PaymentId'
export { default as ReceiptViewer } from '@/pages/Payment/ReceiptViewer'
export { default as MenuId } from '@/pages/Menu/Menus/menuId'
export { default as Reviews } from '@/pages/Review/Reviews'
export { default as EditVenue } from '@/pages/Venue/Venue.edit'
export { default as BasicInfo } from '@/pages/Venue/Edit/BasicInfo'
export { default as ContactImages } from '@/pages/Venue/Edit/ContactImages'
export { default as Shifts } from '@/pages/Shift/Shifts'
// Waiter pages have been removed or renamed. Exports disabled to fix build.
export { default as ShiftId } from '@/pages/Shift/ShiftId'

// Bill
export { default as Orders } from './Order/Orders'
export { default as OrderId } from './Order/OrderId'

// Admin
export { default as AdminDashboard } from '@/pages/Admin/DEPRECATEDAdminDashboard'
export { default as UserManagement } from '@/pages/Admin/DEPRECATEDUserManagement'
export { default as SystemSettings } from '@/pages/Admin/DEPRECATEDSystemSettings'
export { default as VenueManagement } from '@/pages/Admin/DEPRECATEDVenueManagement'
export { default as GlobalConfig } from '@/pages/Admin/DEPRECATEDGlobalConfig'
export { default as SuperAdminManagement } from '@/pages/Admin/SuperAdminManagement'
export { default as SuperAdminVenueEdit } from '@/pages/Admin/SuperAdminVenueEdit'

export { default as Venues } from '@/pages/Venue/Venues'
