export { default as Dashboard } from '@/dashboard'
export { default as ErrorPage } from '@/error-page'
export { default as Login } from '@/pages/Auth/Login'
export { default as Home } from '@/pages/Home'
export { default as Categories } from '@/pages/Menu/Categories/Categories'
export { default as CategoryId } from '@/pages/Menu/Categories/categoryId'
export { default as CreateCategory } from '@/pages/Menu/Categories/createCategory'
export { default as MenuMakerLayout } from '@/pages/Menu/MenuMakerLayout'
export { default as CreateMenu } from '@/pages/Menu/Menus/createMenu'
export { default as Menus } from '@/pages/Menu/Menus/Menus'
export { default as Modifiers } from '@/pages/Menu/Modifiers'
export { default as Overview } from '@/pages/Menu/Overview'
export { default as CreateProduct } from '@/pages/Menu/Products/createProduct'
export { default as ProductId } from '@/pages/Menu/Products/productId'
export { default as Products } from '@/pages/Menu/Products/Products'
export { default as CreateTpv } from '@/pages/Tpv/createTpv'
export { default as Tpv } from '@/pages/Tpv/Tpvs'
export { default as TpvId } from '@/pages/Tpv/TpvId'
export { default as Account } from '@/pages/Account/Account'
export { default as Payments } from '@/pages/Payment/Payments'
export { default as PaymentId } from '@/pages/Payment/PaymentId'
export { default as MenuId } from '@/pages/Menu/Menus/menuId'
export { default as Reviews } from '@/pages/Review/Reviews'
export { default as Waiters } from '@/pages/Waiter/Waiters'
export { default as EditVenue } from '@/pages/Venue/Venue.edit'
export { default as Shifts } from '@/pages/Shift/Shifts'
export { default as WaiterId } from '@/pages/Waiter/waiterId'
export { default as ShiftId } from '@/pages/Shift/ShiftId'

// Bill
export { default as Bills } from './Bill/Bills'
export { default as BillId } from './Bill/BillId'

// Admin
export { default as AdminDashboard } from '@/pages/Admin/AdminDashboard'
export { default as UserManagement } from '@/pages/Admin/UserManagement'
export { default as SystemSettings } from '@/pages/Admin/SystemSettings'
