// src/pages/Settings/Billing/plan/featureIcons.ts
import {
  BarChart3,
  Barcode,
  Bike,
  Boxes,
  Bot,
  Building2,
  CalendarDays,
  ClipboardList,
  Clock,
  CreditCard,
  Download,
  Dumbbell,
  FileText,
  Gift,
  HandCoins,
  Landmark,
  Library,
  LifeBuoy,
  Mail,
  MessageCircle,
  Package,
  Palette,
  Percent,
  PiggyBank,
  Plug,
  PlusCircle,
  RefreshCw,
  Route,
  Scale,
  ScanBarcode,
  ScrollText,
  ShoppingBag,
  Sparkles,
  Star,
  Tag,
  Ticket,
  TrendingUp,
  Users,
  UtensilsCrossed,
  Wallet,
  WifiOff,
  type LucideIcon,
} from 'lucide-react'

/** One icon per catalog entry id (the server's FEATURE_CATALOG). A new entry falls back to a neutral icon. */
const ICONS: Record<string, LucideIcon> = {
  BASE_POS: CreditCard,
  BASE_MENUORDERS: ClipboardList,
  BASE_INVENTORYBASIC: Package,
  BASE_DAILYREPORTS: BarChart3,
  ENTERPRISE_API: Plug,
  ENTERPRISE_SUPPORT: LifeBuoy,
  INVENTORY_TRACKING: Boxes,
  ADVANCED_REPORTS: TrendingUp,
  LOYALTY_PROGRAM: Gift,
  RESERVATIONS: CalendarDays,
  CFDI: FileText,
  COMMISSIONS: HandCoins,
  TABLE_SERVICE: UtensilsCrossed,
  ONLINE_ORDERING: ShoppingBag,
  UPSELL: PlusCircle,
  UPSELL_AI: Sparkles,
  DELIVERY_CHANNELS: Bike,
  MERCHANT_ROUTING_RULES: Route,
  REFERRAL_PROGRAM: Users,
  PROMOTIONS: Percent,
  CUSTOMER_CAMPAIGNS: Mail,
  GOOGLE_REVIEW_REDIRECT: Star,
  AUTO_REORDER: RefreshCw,
  SERIALIZED_INVENTORY: ScanBarcode,
  PRICE_LABELS: Tag,
  SCALE_INTEGRATION: Scale,
  CASH_RECONCILIATION: Wallet,
  BANK_RECONCILIATION: Landmark,
  AVAILABLE_BALANCE: PiggyBank,
  BANKING_HUB: Building2,
  TRANSACTION_EXPORT: Download,
  VENUE_AUDIT_LOG: ScrollText,
  ATTENDANCE_TRACKING: Clock,
  CHATBOT: MessageCircle,
  AI_ASSISTANT_BUBBLE: Bot,
  OFFLINE_LAN_HUB: WifiOff,
  WHITE_LABEL_DASHBOARD: Palette,
  AREA_TICKETS: Ticket,
  VARIABLE_WEIGHT_BARCODE: Barcode,
  MASTER_CATALOG: Library,
  AGGREGATOR_PASSES: Dumbbell,
}

export const FEATURE_ICON_IDS = Object.keys(ICONS)

export const featureIcon = (id: string): LucideIcon => ICONS[id] ?? Sparkles
